import pygame

sprite_R0_s = pygame.image.load('CharSprite/Sprite_R0.png')
sprite_R0 = pygame.transform.scale(sprite_R0_s, (40, 40))
sprite_R1_s = pygame.image.load('CharSprite/Sprite_R1.png')
sprite_R1 = pygame.transform.scale(sprite_R1_s, (40, 40))
sprite_R2_s = pygame.image.load('CharSprite/Sprite_R2.png')
sprite_R2 = pygame.transform.scale(sprite_R2_s, (40, 40))
sprite_L0_s = pygame.image.load('CharSprite/Sprite_L0.png')
sprite_L0 = pygame.transform.scale(sprite_L0_s, (40, 40))
sprite_L1_s = pygame.image.load('CharSprite/Sprite_L1.png')
sprite_L1 = pygame.transform.scale(sprite_L1_s, (40, 40))
sprite_L2_s = pygame.image.load('CharSprite/Sprite_L2.png')
sprite_L2 = pygame.transform.scale(sprite_L2_s, (40, 40))
sprite_U0_s = pygame.image.load('CharSprite/Sprite_U0.png')
sprite_U0 = pygame.transform.scale(sprite_U0_s, (40, 40))
sprite_U1_s = pygame.image.load('CharSprite/Sprite_U1.png')
sprite_U1 = pygame.transform.scale(sprite_U1_s, (40, 40))
sprite_U2_s = pygame.image.load('CharSprite/Sprite_U2.png')
sprite_U2 = pygame.transform.scale(sprite_U2_s, (40, 40))
sprite_D0_s = pygame.image.load('CharSprite/Sprite_D0.png')
sprite_D0 = pygame.transform.scale(sprite_D0_s, (40, 40))
sprite_D1_s = pygame.image.load('CharSprite/Sprite_D1.png')
sprite_D1 = pygame.transform.scale(sprite_D1_s, (40, 40))
sprite_D2_s = pygame.image.load('CharSprite/Sprite_D2.png')
sprite_D2 = pygame.transform.scale(sprite_D2_s, (40, 40))

bg = pygame.image.load('Objects/map - copy.png') # background
