import pygame

#main character
sprite_R0_s = pygame.image.load('CharSprite/Sprite_R0.png')
sprite_R0 = pygame.transform.scale(sprite_R0_s, (40, 40))
sprite_R1_s = pygame.image.load('CharSprite/Sprite_R1.png')
sprite_R1 = pygame.transform.scale(sprite_R1_s, (40, 40))
sprite_R2_s = pygame.image.load('CharSprite/Sprite_R2.png')
sprite_R2 = pygame.transform.scale(sprite_R2_s, (40, 40))
sprite_L0_s = pygame.image.load('CharSprite/Sprite_L0.png')
sprite_L0 = pygame.transform.scale(sprite_L0_s, (40, 40))
sprite_L1_s = pygame.image.load('CharSprite/Sprite_L1.png')
sprite_L1 = pygame.transform.scale(sprite_L1_s, (40, 40))
sprite_L2_s = pygame.image.load('CharSprite/Sprite_L2.png')
sprite_L2 = pygame.transform.scale(sprite_L2_s, (40, 40))
sprite_U0_s = pygame.image.load('CharSprite/Sprite_U0.png')
sprite_U0 = pygame.transform.scale(sprite_U0_s, (40, 40))
sprite_U1_s = pygame.image.load('CharSprite/Sprite_U1.png')
sprite_U1 = pygame.transform.scale(sprite_U1_s, (40, 40))
sprite_U2_s = pygame.image.load('CharSprite/Sprite_U2.png')
sprite_U2 = pygame.transform.scale(sprite_U2_s, (40, 40))
sprite_D0_s = pygame.image.load('CharSprite/Sprite_D0.png')
sprite_D0 = pygame.transform.scale(sprite_D0_s, (40, 40))
sprite_D1_s = pygame.image.load('CharSprite/Sprite_D1.png')
sprite_D1 = pygame.transform.scale(sprite_D1_s, (40, 40))
sprite_D2_s = pygame.image.load('CharSprite/Sprite_D2.png')
sprite_D2 = pygame.transform.scale(sprite_D2_s, (40, 40))

#chicken
chkn_R1_s = pygame.image.load('ChickenSprite/tile006.png')
chkn_R1_a = pygame.transform.scale(chkn_R1_s, (30, 30))
chkn_R1 = pygame.transform.flip(chkn_R1_a, True, False)
chkn_R2_s = pygame.image.load('ChickenSprite/tile005.png')
chkn_R2_a = pygame.transform.scale(chkn_R2_s, (30, 30))
chkn_R2 = pygame.transform.flip(chkn_R2_a, True, False)
chkn_R3_s = pygame.image.load('ChickenSprite/tile004.png')
chkn_R3_a = pygame.transform.scale(chkn_R3_s, (30, 30))
chkn_R3 = pygame.transform.flip(chkn_R3_a, True, False)
chkn_R4_s = pygame.image.load('ChickenSprite/tile003.png')
chkn_R4_a = pygame.transform.scale(chkn_R4_s, (30, 30))
chkn_R4 = pygame.transform.flip(chkn_R4_a, True, False)
chkn_R5_s = pygame.image.load('ChickenSprite/tile002.png')
chkn_R5_a = pygame.transform.scale(chkn_R5_s, (30, 30))
chkn_R5 = pygame.transform.flip(chkn_R5_a, True, False)
chkn_R6_s = pygame.image.load('ChickenSprite/tile001.png')
chkn_R6_a = pygame.transform.scale(chkn_R6_s, (30, 30))
chkn_R6 = pygame.transform.flip(chkn_R6_a, True, False)
chkn_L1_s = pygame.image.load('ChickenSprite/tile006.png')
chkn_L1 = pygame.transform.scale(chkn_L1_s, (30, 30))
chkn_L2_s = pygame.image.load('ChickenSprite/tile005.png')
chkn_L2 = pygame.transform.scale(chkn_L2_s, (30, 30))
chkn_L3_s = pygame.image.load('ChickenSprite/tile004.png')
chkn_L3 = pygame.transform.scale(chkn_L3_s, (30, 30))
chkn_L4_s = pygame.image.load('ChickenSprite/tile003.png')
chkn_L4 = pygame.transform.scale(chkn_L4_s, (30, 30))
chkn_L5_s = pygame.image.load('ChickenSprite/tile002.png')
chkn_L5 = pygame.transform.scale(chkn_L5_s, (30, 30))
chkn_L6_s = pygame.image.load('ChickenSprite/tile001.png')
chkn_L6 = pygame.transform.scale(chkn_L6_s, (30, 30))
chkn_U1_s = pygame.image.load('ChickenSprite/tile014.png')
chkn_U1 = pygame.transform.scale(chkn_U1_s, (30, 30))
chkn_U2_s = pygame.image.load('ChickenSprite/tile015.png')
chkn_U2 = pygame.transform.scale(chkn_U2_s, (30, 30))
chkn_U3_s = pygame.image.load('ChickenSprite/tile016.png')
chkn_U3 = pygame.transform.scale(chkn_U3_s, (30, 30))
chkn_U4_s = pygame.image.load('ChickenSprite/tile017.png')
chkn_U4 = pygame.transform.scale(chkn_U4_s, (30, 30))
chkn_U5_s = pygame.image.load('ChickenSprite/tile018.png')
chkn_U5 = pygame.transform.scale(chkn_U5_s, (30, 30))
chkn_U6_s = pygame.image.load('ChickenSprite/tile019.png')
chkn_U6 = pygame.transform.scale(chkn_U6_s, (30, 30))
chkn_U7_s = pygame.image.load('ChickenSprite/tile020.png')
chkn_U7 = pygame.transform.scale(chkn_U7_s, (30, 30))
chkn_D1_s = pygame.image.load('ChickenSprite/tile007.png')
chkn_D1 = pygame.transform.scale(chkn_D1_s, (30, 30))
chkn_D2_s = pygame.image.load('ChickenSprite/tile008.png')
chkn_D2 = pygame.transform.scale(chkn_D2_s, (30, 30))
chkn_D3_s = pygame.image.load('ChickenSprite/tile009.png')
chkn_D3 = pygame.transform.scale(chkn_D3_s, (30, 30))
chkn_D4_s = pygame.image.load('ChickenSprite/tile010.png')
chkn_D4 = pygame.transform.scale(chkn_D4_s, (30, 30))
chkn_D5_s = pygame.image.load('ChickenSprite/tile011.png')
chkn_D5 = pygame.transform.scale(chkn_D5_s, (30, 30))
chkn_D6_s = pygame.image.load('ChickenSprite/tile012.png')
chkn_D6 = pygame.transform.scale(chkn_D6_s, (30, 30))
chkn_D7_s = pygame.image.load('ChickenSprite/tile013.png')
chkn_D7 = pygame.transform.scale(chkn_D7_s, (30, 30))

#coop
coop_o_s = pygame.image.load('Objects/coopDoorOpen.png')
coop_o = pygame.transform.scale(coop_o_s, (200, 200))
coop_cq_s = pygame.image.load('Objects/coopDoorClosing1.png')
coop_cq = pygame.transform.scale(coop_cq_s, (200, 200))
coop_ch_s = pygame.image.load('Objects/coopDoorClosing2.png')
coop_ch = pygame.transform.scale(coop_ch_s, (200, 200))
coop_ct_s = pygame.image.load('Objects/coopDoorClosing3.png')
coop_ct = pygame.transform.scale(coop_ct_s, (200, 200))
coop_c_s = pygame.image.load('Objects/coopDoorClosed.png')
coop_c = pygame.transform.scale(coop_c_s, (200, 200))

#bell
bell_s = pygame.image.load('Objects/bell.png')
bellSprite = pygame.transform.scale(bell_s, (50, 50))

#market stand
market_s = pygame.image.load('Objects/market.png')
marketSprite = pygame.transform.scale(market_s, (75,75))




bg = pygame.image.load('Objects/map - copy.png') # background
rockSprite = pygame.image.load('Objects/rock.png')
